<a href="https://colab.research.google.com/github/Young4424/Machine-Learning-Deep-learning-Myself/blob/main/02_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EC%9D%98_%EC%9D%B4%ED%95%B4%EC%99%80_%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Basic

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Data Description  : https://github.com/PacktPublishing/Pandas-Cookbook/blob/master/dataset_descriptions.ipynb

![DataFrame Anatomy](https://static.packt-cdn.com/products/9781784393878/graphics/assets/c91f4c94-a6ef-44b4-97bc-aa52130e0d3a.png)

## Pandas 구성객체

In [3]:
PATH = '/content/drive/MyDrive/인공지능 엔지니어 양성 교육/Day1_데이터 분석/data/'

In [4]:
import pandas as pd

In [71]:
movie = pd.read_csv(PATH + 'movie.csv')

In [11]:
movie.head() # 데이터 잘 있는지 확인

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

## 데이터 이해하기

### 구성요소

In [13]:
movie.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [14]:
movie.index # 0 ~ 4916까지 매겨있음

RangeIndex(start=0, stop=4916, step=1)

In [17]:
movie.values # 2차원 배열,첫 번재 데이터 타입을 따라감

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

### 형태 및 데이터 타입

In [18]:
movie.shape

(4916, 28)

In [19]:
movie.size # 넓이

137648

In [21]:
movie.dtypes # 각 열이 어떤 자료형으로 구성되어 있는지 확인(object - 문자열)

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [23]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   object
 1   director_name              4814 non-null   object
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object
 10  actor_1_name               4909 non-null   object
 11  movie_title                4916 non-null   object
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   object
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   object
 17  movie_imdb_link            4916 non-null   object
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4904 non-null   object
 20  country                    4911 non-null   object
 21  content_rating             4616 non-null   object
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

## 행(Row), 열(Column) 다루기

### Selecting

#### 열 이름으로 선택

In [25]:
movie['director_name'] # index와 같이 붙혀서 나오는 것 - series

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [74]:
movie.loc[2] # 행으로 index 선택함

color                                                                    Color
director_name                                                       Sam Mendes
num_critic_for_reviews                                                   602.0
duration                                                                 148.0
director_facebook_likes                                                    0.0
actor_3_facebook_likes                                                   161.0
actor_2_name                                                      Rory Kinnear
actor_1_facebook_likes                                                 11000.0
gross                                                              200074175.0
genres                                               Action|Adventure|Thriller
actor_1_name                                                   Christoph Waltz
movie_title                                                            Spectre
num_voted_users                                                         275868
cast_total_facebook_likes                                                11700
actor_3_name                                                  Stephanie Sigman
facenumber_in_poster                                                       1.0
plot_keywords                              bomb|espionage|sequel|spy|terrorist
movie_imdb_link              http://www.imdb.com/title/tt2379713/?ref_=fn_t...
num_user_for_reviews                                                     994.0
language                                                               English
country                                                                     UK
content_rating                                                           PG-13
budget                                                             245000000.0
title_year                                                              2015.0
actor_2_facebook_likes                                                   393.0
imdb_score                                                                 6.8
aspect_ratio                                                              2.35
movie_facebook_likes                                                     85000
Name: 2, dtype: object

In [75]:
movie[['director_name','movie_title']] # 데이터 프레임, 0번 index에 값 두개 붙음

          director_name                                 movie_title
0         James Cameron                                      Avatar
1        Gore Verbinski    Pirates of the Caribbean: At World's End
2            Sam Mendes                                     Spectre
3     Christopher Nolan                       The Dark Knight Rises
4           Doug Walker  Star Wars: Episode VII - The Force Awakens
...                 ...                                         ...
4911        Scott Smith                     Signed Sealed Delivered
4912                NaN                               The Following
4913   Benjamin Roberds                        A Plague So Pleasant
4914        Daniel Hsia                            Shanghai Calling
4915           Jon Gunn                           My Date with Drew

[4916 rows x 2 columns]

#### 메서드를 이용한 열 선택

##### `.select_dtypes`

In [31]:
movie.select_dtypes(object) # 특정 데이터 타입을 가진 열들만 선택함

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,Daphne Zuniga,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,Crystal Lowe,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,English,Canada,NaN
4912,Color,NaN,Valorie Curry,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,Sam Underwood,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,English,USA,TV-14
4913,Color,Benjamin Roberds,Maxwell Moody,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,David Chandler,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,English,USA,NaN
4914,Color,Daniel Hsia,Daniel Henney,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,Eliza Coupe,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,English,USA,PG-13
4915,Color,Jon Gunn,Brian Herzlinger,Documentary,John August,My Date with Drew,Jon Gunn,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,English,USA,PG

##### `.filter`

In [33]:
movie.filter(like = 'facebook') # 특정 단어가 들어간 컬럼만 선택

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
4911,2.0,318.0,637.0,2283,470.0,84
4912,NaN,319.0,841.0,1753,593.0,32000
4913,0.0,0.0,0.0,0,0.0,16
4914,0.0,489.0,946.0,2386,719.0,660
4915,16.0,16.0,86.0,163,23.0,456

In [34]:
movie.filter(regex = '\d') # 패턴을 인식 받아서 분류함, ex) 열 이름에 숫자가 들어가 있으면 선택

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0
...,...,...,...,...,...,...
4911,318.0,Daphne Zuniga,637.0,Eric Mabius,Crystal Lowe,470.0
4912,319.0,Valorie Curry,841.0,Natalie Zea,Sam Underwood,593.0
4913,0.0,Maxwell Moody,0.0,Eva Boehnke,David Chandler,0.0
4914,489.0,Daniel Henney,946.0,Alan Ruck,Eliza Coupe,719.0
4915,16.0,Brian Herzlinger,86.0,John August,Jon Gunn,23.0

### Renaming

In [40]:
movie.rename(columns = {'color': '색상'},index = {0:'영번'})

,색상,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
영번,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [42]:
temp = movie.iloc[:,:3] # 행 기준으로 모두,열 기준으로 3번까지, 한번에 리스트를 통째로 덮어서 바꿈

In [44]:
temp.columns = ['색상','감독명','비판댓글수']

In [46]:
temp.index = temp['감독명'] # 감독명이 인덱스가 됨

In [47]:
temp.head()

                      색상                감독명  비판댓글수
감독명
James Cameron      Color      James Cameron  723.0
Gore Verbinski     Color     Gore Verbinski  302.0
Sam Mendes         Color         Sam Mendes  602.0
Christopher Nolan  Color  Christopher Nolan  813.0
Doug Walker          NaN        Doug Walker    NaN

연습문제 1. `director_name`과 `duration`의 이름을 각각 `감독명`, `상영시간`으로 변경하고, `movie_title`을 인덱스로 변경해보세요.

In [55]:
movie = movie.rename(columns = {'director_name':'감독명', 'duration':'상영시간'})

In [57]:
movie.index = movie['movie_title']

In [58]:
movie.head()

,color,감독명,num_critic_for_reviews,상영시간,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [60]:
movie.reset_index(drop = True) # drop = True를 해야 index 값이 초기화가 된다.

,color,감독명,num_critic_for_reviews,상영시간,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### Creating & Deleting

In [76]:
movie['새로운열'] = 100 # 제일 뒤에 붙음, broadcasting 으로 붙음

In [63]:
movie['새로운열'] = [100,100,100] # error

ValueError: ignored

In [77]:
movie['새로운열']

0       100
1       100
2       100
3       100
4       100
       ...
4911    100
4912    100
4913    100
4914    100
4915    100
Name: 새로운열, Length: 4916, dtype: int64

In [78]:
import numpy as np

In [79]:
movie['새로운열'] = np.random.randint(1,100,4916)

In [81]:
movie['새로운열']

0       59
1       86
2       62
3       35
4       87
        ..
4911    22
4912    45
4913    33
4914    30
4915    27
Name: 새로운열, Length: 4916, dtype: int64

In [82]:
movie.drop(columns = '새로운열') # columns, index 붙혀야 지울 수 있음

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### Indexing / Slicing

|Methods|Description|
|--|--|
|`df[value]`|하나의 컬럼 또는 여러 컬럼 선택|
|`df.loc[value]`|value값(Index값 기준)으로 행의 부분집합을 선택|
|`df.loc[:, value]`|value값으로 열의 부분집합을 선택|
|`df.loc[value1, value2]`|value값으로 행과 열의 부분집합을 선택|
|`df.iloc[where]`|where 값(순서값 기준)으로 행의 부분집합 선택|
|`df.iloc[:, where]`|where 값으로 열의 부분집합 선택|
|`df.iloc[where1, where2]`|where 값으로 행과 열의 부분집합을 선택|

#### `.loc` 함수를 이용한 인덱싱 / 슬라이싱

In [83]:
# 이름을 가지고 선택함
movie = pd.read_csv(PATH + 'movie.csv')

In [86]:
movie.loc[0,'movie_title'] # 0번 행에 있는 'movie_title을 선택

'Avatar'

In [89]:
movie.loc[0:10,'color':'duration'] # '10번'을 포함해서 선택함

    color      director_name  num_critic_for_reviews  duration
0   Color      James Cameron                   723.0     178.0
1   Color     Gore Verbinski                   302.0     169.0
2   Color         Sam Mendes                   602.0     148.0
3   Color  Christopher Nolan                   813.0     164.0
4     NaN        Doug Walker                     NaN       NaN
5   Color     Andrew Stanton                   462.0     132.0
6   Color          Sam Raimi                   392.0     156.0
7   Color       Nathan Greno                   324.0     100.0
8   Color        Joss Whedon                   635.0     141.0
9   Color        David Yates                   375.0     153.0
10  Color        Zack Snyder                   673.0     183.0

#### `.iloc`함수를 이용한 인덱싱 / 슬라이싱

In [92]:
# index loc, 순서 이용

movie.iloc[0:10,0] # '0번째부터 10번째'까지, 0~9

# movie.iloc[0:10,'color'] 안됨

0    Color
1    Color
2    Color
3    Color
4      NaN
5    Color
6    Color
7    Color
8    Color
9    Color
Name: color, dtype: object

#### 특정 조건에 해당하는 행 선택 - 불리언 인덱싱(중요!!)

In [97]:
# critic이 700개 넘어가는 걸 선택

movie[movie['num_critic_for_reviews'] >= 700]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
30,Color,Sam Mendes,750.0,143.0,0.0,393.0,Helen McCrory,883.0,304360277.0,Action|Adventure|Thriller,...,1498.0,English,UK,PG-13,200000000.0,2012.0,563.0,7.8,2.35,80000
96,Color,Christopher Nolan,712.0,169.0,22000.0,6000.0,Anne Hathaway,11000.0,187991439.0,Adventure|Drama|Sci-Fi,...,2725.0,English,USA,PG-13,165000000.0,2014.0,11000.0,8.6,2.35,349000
128,Color,George Miller,739.0,120.0,750.0,943.0,Charlize Theron,27000.0,153629485.0,Action|Adventure|Sci-Fi|Thriller,...,1588.0,English,Australia,R,150000000.0,2015.0,9000.0,8.1,2.35,191000
224,Color,Ridley Scott,775.0,124.0,0.0,641.0,Charlize Theron,13000.0,126464904.0,Adventure|Mystery|Sci-Fi,...,2326.0,English,USA,R,130000000.0,2012.0,9000.0,7.0,2.35,97000
243,Color,Alfonso Cuarón,738.0,91.0,0.0,13.0,Basher Savage,39.0,274084951.0,Adventure|Drama|Sci-Fi|Thriller,...,1885.0,English,UK,PG-13,100000000.0,2013.0,23.0,7.8,2.35,147000
293,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,2.35,199000

In [102]:
movie[movie['imdb_score']>=9.0]['movie_title'] # 9.0이 넘는 영화 타이틀 보여줘

66               The Dark Knight
1920    The Shawshank Redemption
2725            Towering Inferno
2779                     Dekalog
2791      The Godfather: Part II
3402               The Godfather
3415                       Fargo
4312        Kickboxer: Vengeance
Name: movie_title, dtype: object

In [105]:
c1 = (movie['actor_1_facebook_likes'] >= 3000)
c2 = (movie['country'] == 'USA')


movie[c1 & c2]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4781,Color,David G. Evans,25.0,101.0,0.0,16.0,Chris Thomas,77000.0,2428241.0,Drama,...,26.0,English,USA,PG-13,200000.0,2010.0,21.0,6.4,NaN,0
4793,Color,Marianna Palka,38.0,86.0,123.0,782.0,Martin Starr,3000.0,15542.0,Comedy|Drama|Romance,...,51.0,English,USA,R,NaN,2008.0,985.0,6.5,1.85,0
4839,Color,E.L. Katz,193.0,88.0,3.0,307.0,Ethan Embry,3000.0,59379.0,Comedy|Crime|Drama|Horror|Thriller,...,52.0,English,USA,Not Rated,200000.0,2013.0,982.0,6.8,2.35,0
4853,Color,Joe Swanberg,65.0,82.0,217.0,442.0,Lena Dunham,10000.0,30084.0,Comedy|Drama,...,23.0,English,USA,R,70000.0,2014.0,969.0,5.6,1.85,812
4872,Color,Kevin Jordan,21.0,90.0,4.0,113.0,Christa Miller,20000.0,277233.0,Comedy|Romance,...,26.0,English,USA,R,40000.0,1999.0,467.0,7.6,1.85,0

#### `query`문을 이용한 행 선택

In [107]:
director = ['Gore Verbinski','Christopher Nolan']

In [108]:
movie.query('director_name == @director') # 디렉터 선택할 때 간단하게


# c1 = movie['director_name'] == 'Gore Verbinski'
# c2 = movie['dircector_name'] == 'Christopher Nolan'

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
66,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,4667.0,English,USA,PG-13,185000000.0,2008.0,13000.0,9.0,2.35,37000
96,Color,Christopher Nolan,712.0,169.0,22000.0,6000.0,Anne Hathaway,11000.0,187991439.0,Adventure|Drama|Sci-Fi,...,2725.0,English,USA,PG-13,165000000.0,2014.0,11000.0,8.6,2.35,349000
97,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,2803.0,English,USA,PG-13,160000000.0,2010.0,27000.0,8.8,2.35,175000
120,Color,Christopher Nolan,478.0,128.0,22000.0,11000.0,Liam Neeson,23000.0,205343774.0,Action|Adventure,...,2685.0,English,USA,PG-13,150000000.0,2005.0,14000.0,8.3,2.35,15000
180,Color,Gore Verbinski,362.0,107.0,563.0,939.0,Ray Winstone,40000.0,123207194.0,Adventure|Animation|Comedy|Family|Western,...,337.0,English,USA,PG,135000000.0,2011.0,1000.0,7.2,2.35,26000
202,Color,Gore Verbinski,271.0,143.0,563.0,1000.0,Orlando Bloom,40000.0,305388685.0,Action|Adventure|Fantasy,...,2113.0,English,USA,PG-13,140000000.0,2003.0,5000.0,8.1,2.35,10000
1057,Color,Christopher Nolan,185.0,118.0,22000.0,319.0,Maura Tierney,14000.0,67263182.0,Drama|Mystery|Thriller,...,651.0,English,USA,R,46000000.0,2002.0,509.0,7.2,2.35,0
1209,Color,Gore Verbinski,125.0,123.0,563.0,8000.0,Brad Pitt,24000.0,66808615.0,Adventure|Comedy|Crime|Romance,...,344.0,English,USA,R,34000000.0,2001.0,11000.0,6.1,2.35,2000
1222,Color,Christopher Nolan,341.0,130.0,22000.0,19000.0,Hugh Jackman,23000.0,53082743.0,Drama|Mystery|Sci-Fi|Thriller,...,1100.0,English,USA,PG-13,40000000.0,2006.0,20000.0,8.5,2.35,49000
2250,Color,Gore Verbinski,156.0,102.0,563.0,385.0,Hope Davis,12000.0,12469811.0,Comedy|Drama,...,316.0,English,USA,R,22000000.0,2005.0,442.0,6.6,1.85,0
3646,Black and White,Christopher Nolan,274.0,113.0,22000.0,379.0,Thomas Lennon,716.0,25530884.0,Mystery|Thriller,...,2067.0,English,USA,R,9000000.0,2000.0,651.0,8.5,2.35,40000

In [106]:
movie.query("actor_1_facebook_likes >= 3000 and country == 'USA'")

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4781,Color,David G. Evans,25.0,101.0,0.0,16.0,Chris Thomas,77000.0,2428241.0,Drama,...,26.0,English,USA,PG-13,200000.0,2010.0,21.0,6.4,NaN,0
4793,Color,Marianna Palka,38.0,86.0,123.0,782.0,Martin Starr,3000.0,15542.0,Comedy|Drama|Romance,...,51.0,English,USA,R,NaN,2008.0,985.0,6.5,1.85,0
4839,Color,E.L. Katz,193.0,88.0,3.0,307.0,Ethan Embry,3000.0,59379.0,Comedy|Crime|Drama|Horror|Thriller,...,52.0,English,USA,Not Rated,200000.0,2013.0,982.0,6.8,2.35,0
4853,Color,Joe Swanberg,65.0,82.0,217.0,442.0,Lena Dunham,10000.0,30084.0,Comedy|Drama,...,23.0,English,USA,R,70000.0,2014.0,969.0,5.6,1.85,812
4872,Color,Kevin Jordan,21.0,90.0,4.0,113.0,Christa Miller,20000.0,277233.0,Comedy|Romance,...,26.0,English,USA,R,40000.0,1999.0,467.0,7.6,1.85,0

연습문제 1. (1) 컬러영화이면서 (2) 불어를 사용하고, (3) 장르가 코메디인 영화는 무엇인가요?

In [116]:
movie.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [114]:
# 컬러영화, 불어, 장르를 표현하는 컬럼명 확인
# 컬러는 어떻게 코딩되어있고, 불어, 코메디
# French, Comedy

# color, langauge, genres

c1 = movie['color'] == 'Color'
c2 = movie['language'] == 'French'
c3 = movie['genres'] == 'Comedy'

movie[c1&c2&c3]['movie_title']

3256    Barbecue
Name: movie_title, dtype: object

#### 사전순으로 슬라이싱

In [131]:
movie = movie.set_index('movie_title')

In [132]:
movie = movie.sort_index()

In [133]:
movie.loc['A':'C'] # sort를 먼저 하고 a부터 c까지 해야 가능함

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
A Beautiful Mind,Color,Ron Howard,205.0,135.0,2000.0,535.0,Austin Pendleton,1000.0,170708996.0,Biography|Drama,...,1171.0,English,USA,PG-13,58000000.0,2001.0,592.0,8.2,1.85,29000
A Beginner's Guide to Snuff,Color,Mitchell Altieri,NaN,87.0,9.0,165.0,Luke Edwards,467.0,NaN,Comedy|Horror|Thriller,...,NaN,English,USA,NaN,NaN,2016.0,258.0,8.7,NaN,8
A Better Life,Color,Chris Weitz,94.0,98.0,129.0,221.0,Eddie 'Piolin' Sotelo,749.0,1754319.0,Drama|Romance,...,81.0,English,USA,PG-13,10000000.0,2011.0,252.0,7.2,1.85,0
A Bridge Too Far,Black and White,Richard Attenborough,56.0,175.0,0.0,14.0,Dirk Bogarde,385.0,50800000.0,Drama|History|War,...,210.0,English,USA,PG,26000000.0,1977.0,232.0,7.4,2.35,0
A Bug's Life,Color,John Lasseter,117.0,95.0,487.0,1000.0,Madeline Kahn,18000.0,162792677.0,Adventure|Animation|Comedy|Family|Fantasy,...,317.0,English,USA,G,120000000.0,1998.0,1000.0,7.2,2.35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
But I'm a Cheerleader,Color,Jamie Babbit,99.0,85.0,91.0,849.0,Clea DuVall,1000.0,2199853.0,Comedy|Drama,...,186.0,English,USA,R,1200000.0,1999.0,1000.0,6.6,1.85,0
Butch Cassidy and the Sundance Kid,Color,George Roy Hill,130.0,110.0,131.0,399.0,Ted Cassidy,640.0,102308900.0,Biography|Crime|Drama|Western,...,309.0,English,USA,M,6000000.0,1969.0,566.0,8.1,2.35,0
Butterfly,Color,Matt Cimber,15.0,108.0,32.0,180.0,June Lockhart,602.0,NaN,Crime|Drama,...,18.0,English,USA,R,NaN,1982.0,427.0,4.5,1.85,76
Butterfly Girl,Color,Cary Bell,NaN,78.0,0.0,0.0,Stacie Evans,0.0,NaN,Documentary,...,1.0,English,USA,NaN,180000.0,2014.0,0.0,8.7,NaN,88
By the Sea,Color,Angelina Jolie Pitt,131.0,122.0,11000.0,188.0,Angelina Jolie Pitt,11000.0,531009.0,Drama|Romance,...,61.0,English,USA,R,10000000.0,2015.0,11000.0,5.3,2.35,0

## 데이터 기본연산

In [135]:
tmp = movie.select_dtypes('number') # int, float 모두 선택 가능

In [139]:
(tmp / 100).round(2) # 마치 100으로 채워져 있는 행렬로 계산시켜줌, broadcasting, 둘째자리 까지 반올림

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,
#Horror,0.35,1.01,0.37,0.56,5.01,NaN,15.47,10.44,0.01,0.42,15000.0,20.15,4.18,0.03,NaN,7.5
10 Cloverfield Lane,4.11,1.04,0.16,0.82,140.00,718972.15,1268.93,145.04,0.00,4.40,150000.0,20.16,3.38,0.07,0.02,330.0
10 Days in a Madhouse,0.01,1.11,0.00,2.47,10.00,146.16,3.14,20.59,0.01,0.10,120000.0,20.15,4.45,0.08,0.02,260.0
10 Things I Hate About You,1.33,0.97,0.19,8.35,230.00,381761.08,2220.99,379.07,0.06,5.49,160000.0,19.99,130.00,0.07,0.02,100.0
"10,000 B.C.",NaN,0.22,0.00,NaN,0.05,NaN,0.06,0.05,0.00,NaN,NaN,NaN,NaN,0.07,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
[Rec] 2,2.22,0.85,0.57,0.06,0.37,270.24,555.97,0.73,0.00,1.48,56000.0,20.09,0.09,0.07,0.02,40.0
eXistenZ,1.96,1.15,0.00,7.16,10.00,28404.17,774.93,29.90,0.00,5.27,310000.0,19.99,9.00,0.07,0.02,60.0
xXx,1.91,1.32,3.57,2.12,140.00,1412040.16,1425.69,147.90,0.00,7.37,700000.0,20.02,2.23,0.06,0.02,100.0
xXx: State of the Union,0.77,1.01,0.93,2.18,2.87,260829.14,513.49,9.93,0.02,2.13,870000.0,20.05,2.33,0.04,0.02,0.0
Æon Flux,1.78,0.93,0.45,3.52,90.00,258579.87,1106.14,101.85,0.00,5.32,620000.0,20.05,4.60,0.06,0.02,0.0

In [141]:
tmp_mean = tmp.mean(axis = 0) # 세로 = 0, 가로 기준 = 1

In [144]:
tmp.div(tmp_mean).round(2) # 각 열에 mean이 적용됨, 반올림 소수점 둘째자리

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,
#Horror,0.25,0.94,0.05,0.09,0.08,NaN,0.02,0.11,0.73,0.16,0.04,1.01,0.26,0.51,NaN,0.10
10 Cloverfield Lane,2.98,0.97,0.02,0.13,2.16,1.51,1.54,1.51,0.00,1.64,0.41,1.01,0.21,1.13,1.06,4.49
10 Days in a Madhouse,0.01,1.04,0.00,0.39,0.15,0.00,0.00,0.21,0.73,0.04,0.33,1.01,0.27,1.17,0.83,3.54
10 Things I Hate About You,0.96,0.91,0.03,1.32,3.54,0.80,2.69,3.96,4.36,2.05,0.44,1.00,8.02,1.12,0.83,1.36
"10,000 B.C.",NaN,0.21,0.00,NaN,0.00,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,1.12,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
[Rec] 2,1.61,0.79,0.08,0.01,0.01,0.00,0.67,0.01,0.00,0.55,0.15,1.00,0.01,1.03,0.83,0.54
eXistenZ,1.42,1.07,0.00,1.13,0.15,0.06,0.94,0.31,0.00,1.97,0.85,1.00,0.55,1.06,0.83,0.82
xXx,1.38,1.23,0.52,0.34,2.16,2.96,1.73,1.54,0.00,2.75,1.92,1.00,0.14,0.90,1.06,1.36
xXx: State of the Union,0.56,0.94,0.13,0.35,0.04,0.55,0.62,0.10,1.45,0.80,2.38,1.00,0.14,0.67,1.06,0.00
Æon Flux,1.29,0.87,0.07,0.56,1.39,0.54,1.34,1.06,0.00,1.99,1.70,1.00,0.28,0.85,1.06,0.00

In [149]:
tmp['num_critic_for_reviews'].quantile([.25,.5,.75]) # 1,2,3 사분위수를 알려줘

0.25     49.0
0.50    108.0
0.75    191.0
Name: num_critic_for_reviews, dtype: float64

# 데이터 분석

#### Cleaning

In [152]:
movie = pd.read_csv(PATH + 'movie.csv')

##### 결측값

In [154]:
movie.isna().sum() # True가 1이므로 결측값 개수를 알 수 있다.

color                         19
director_name                102
num_critic_for_reviews        49
duration                      15
director_facebook_likes      102
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        862
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                152
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               300
budget                       484
title_year                   106
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 326
movie_facebook_likes           0
dtype: int64

In [161]:
movie.dropna(subset = ['director_name']).isna().sum() # 결측값 다 날려줘, subset = 특정 부분만 날려줘

color                         17
director_name                  0
num_critic_for_reviews        44
duration                      13
director_facebook_likes        0
actor_3_facebook_likes        20
actor_2_name                  11
actor_1_facebook_likes         7
gross                        762
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  20
facenumber_in_poster          13
plot_keywords                143
movie_imdb_link                0
num_user_for_reviews          19
language                      11
country                        3
content_rating               262
budget                       390
title_year                     4
actor_2_facebook_likes        11
imdb_score                     0
aspect_ratio                 307
movie_facebook_likes           0
dtype: int64

In [162]:
movie.fillna(0) # 결측값에 0을 넣는다.

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,0,Doug Walker,0.0,0.0,131.0,0.0,Rob Walker,131.0,0.0,Documentary,...,0.0,0,0,0,0.0,0.0,12.0,7.1,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,0.0,Comedy|Drama,...,6.0,English,Canada,0,0.0,2013.0,470.0,7.7,0.00,84
4912,Color,0,43.0,43.0,0.0,319.0,Valorie Curry,841.0,0.0,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,0.0,0.0,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,0.0,Drama|Horror|Thriller,...,3.0,English,USA,0,1400.0,2013.0,0.0,6.3,0.00,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,0.0,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

##### 중복값

In [163]:
movie.duplicated() # 각 행에 대한 중복값이 있는지 물어봄

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912    False
4913    False
4914    False
4915    False
Length: 4916, dtype: bool

In [164]:
movie['director_name'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912     True
4913    False
4914    False
4915     True
Name: director_name, Length: 4916, dtype: bool

In [166]:
movie['director_name'].drop_duplicates()

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4907     Neill Dela Llana
4909      Anthony Vallone
4911          Scott Smith
4913     Benjamin Roberds
4914          Daniel Hsia
Name: director_name, Length: 2398, dtype: object

### Describe

In [168]:
movie.describe().T # Transpose로 보기 쉽게, 문자열 데이터는 빠져있음

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,4867.0,1.379889e+02,1.202394e+02,1.00,49.00,108.00,191.00,8.130000e+02
duration,4901.0,1.070908e+02,2.528602e+01,7.00,93.00,103.00,118.00,5.110000e+02
director_facebook_likes,4814.0,6.910145e+02,2.832954e+03,0.00,7.00,48.00,189.75,2.300000e+04
actor_3_facebook_likes,4893.0,6.312763e+02,1.625875e+03,0.00,132.00,366.00,633.00,2.300000e+04
actor_1_facebook_likes,4909.0,6.494488e+03,1.510699e+04,0.00,607.00,982.00,11000.00,6.400000e+05
gross,4054.0,4.764451e+07,6.737255e+07,162.00,5019656.25,25043962.00,61108412.75,7.605058e+08
num_voted_users,4916.0,8.264492e+04,1.383222e+05,5.00,8361.75,33132.50,93772.75,1.689764e+06
cast_total_facebook_likes,4916.0,9.579816e+03,1.816432e+04,0.00,1394.75,3049.00,13616.75,6.567300e+05
facenumber_in_poster,4903.0,1.377320e+00,2.023826e+00,0.00,0.00,1.00,2.00,4.300000e+01
num_user_for_reviews,4895.0,2.676688e+02,3.729348e+02,1.00,64.00,153.00,320.50,5.060000e+03
budget,4432.0,3.654749e+07,1.002427e+08,218.00,6000000.00,19850000.00,43000000.00,4.200000e+09
title_year,4810.0,2.002448e+03,1.245398e+01,1916.00,1999.00,2005.00,2011.00,2.016000e+03
actor_2_facebook_likes,4903.0,1.621924e+03,4.011300e+03,0.00,277.00,593.00,912.00,1.370000e+05
imdb_score,4916.0,6.437429e+00,1.127802e+00,1.60,5.80,6.60,7.20,9.500000e+00
aspect_ratio,4590.0,2.222349e+00,1.402940e+00,1.18,1.85,2.35,2.35,1.600000e+01
movie_facebook_likes,4916.0,7.348294e+03,1.920602e+04,0.00,0.00,159.00,2000.00,3.490000e+05

In [169]:
movie.describe(include = object).T #

,count,unique,top,freq
color,4897,2,Color,4693
director_name,4814,2397,Steven Spielberg,26
actor_2_name,4903,3030,Morgan Freeman,18
genres,4916,914,Drama,233
actor_1_name,4909,2095,Robert De Niro,48
movie_title,4916,4916,Avatar,1
actor_3_name,4893,3519,Steve Coogan,8
plot_keywords,4764,4756,based on novel,4
movie_imdb_link,4916,4916,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,1
language,4904,47,English,4582
country,4911,65,USA,3710
content_rating,4616,18,R,2067

### Selecting Subset

In [171]:
movie.nlargest(10,'num_critic_for_reviews') # 10개를 뽑는데, num critic reviews 기준으로

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
224,Color,Ridley Scott,775.0,124.0,0.0,641.0,Charlize Theron,13000.0,126464904.0,Adventure|Mystery|Sci-Fi,...,2326.0,English,USA,R,130000000.0,2012.0,9000.0,7.0,2.35,97000
293,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,2.35,199000
30,Color,Sam Mendes,750.0,143.0,0.0,393.0,Helen McCrory,883.0,304360277.0,Action|Adventure|Thriller,...,1498.0,English,UK,PG-13,200000000.0,2012.0,563.0,7.8,2.35,80000
128,Color,George Miller,739.0,120.0,750.0,943.0,Charlize Theron,27000.0,153629485.0,Action|Adventure|Sci-Fi|Thriller,...,1588.0,English,Australia,R,150000000.0,2015.0,9000.0,8.1,2.35,191000
243,Color,Alfonso Cuarón,738.0,91.0,0.0,13.0,Basher Savage,39.0,274084951.0,Adventure|Drama|Sci-Fi|Thriller,...,1885.0,English,UK,PG-13,100000000.0,2013.0,23.0,7.8,2.35,147000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
96,Color,Christopher Nolan,712.0,169.0,22000.0,6000.0,Anne Hathaway,11000.0,187991439.0,Adventure|Drama|Sci-Fi,...,2725.0,English,USA,PG-13,165000000.0,2014.0,11000.0,8.6,2.35,349000
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000

In [172]:
movie.nsmallest(10,'num_critic_for_reviews')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
98,Color,Hideaki Anno,1.0,120.0,28.0,12.0,Shin'ya Tsukamoto,544.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,...,13.0,Japanese,Japan,NaN,NaN,2016.0,106.0,8.2,2.35,0
197,Color,Matt Birch,1.0,NaN,0.0,159.0,Dave Legeno,10000.0,NaN,Action|Fantasy,...,2.0,English,UK,NaN,NaN,2011.0,570.0,7.5,NaN,40
363,Color,Timur Bekmambetov,1.0,141.0,335.0,635.0,Ayelet Zurer,11000.0,NaN,Adventure|Drama|History,...,1.0,English,USA,PG-13,NaN,2016.0,745.0,6.1,2.35,0
2783,Color,NaN,1.0,41.0,NaN,2.0,Marian Dziedziel,70.0,NaN,Action|Crime|Drama|Thriller,...,2.0,Polish,Poland,NaN,NaN,NaN,2.0,7.4,NaN,64
2964,Color,Timothy Hines,1.0,111.0,0.0,247.0,Kelly LeBrock,1000.0,14616.0,Drama,...,10.0,English,USA,R,12000000.0,2015.0,445.0,7.5,1.85,26000
3246,Color,NaN,1.0,30.0,NaN,140.0,Katherine Kelly Lang,177.0,NaN,Drama|Romance,...,54.0,English,USA,TV-14,NaN,NaN,170.0,3.5,1.78,748
3763,Color,Shekar,1.0,NaN,0.0,0.0,Diganth,5.0,NaN,Comedy|Romance,...,1.0,Kannada,India,NaN,NaN,2013.0,0.0,7.1,NaN,2
3894,Color,Alan Jacobs,1.0,92.0,2.0,601.0,Laz Alonso,881.0,NaN,Drama,...,6.0,English,USA,R,NaN,2009.0,826.0,7.3,1.85,237
3933,Color,NaN,1.0,45.0,NaN,119.0,Ash Cook,773.0,NaN,Drama|Thriller,...,4.0,English,UK,NaN,NaN,NaN,133.0,7.3,NaN,405
3955,Color,Jennifer Finnigan,1.0,97.0,246.0,491.0,Kenan Thompson,756.0,NaN,Comedy,...,3.0,English,USA,NaN,3300000.0,2014.0,521.0,4.5,16.00,0

연습문제 1. `movie` 데이터에서 (1) IMDB 평점 기준 상위 5개의 영화 중 (2) 영화배우들의 페이스북 좋아요 수의 평균 값을 구해보세요.

연습문제 2. 1번 문제에서 평균 영화배우 좋아요 수가 가장 많은 영화는 무엇인가요?

In [186]:
movie.columns
# actor 1,2,3 facebook_likes

movie.nlargest(5,'imdb_score').filter(like = 'actor').filter(like = 'facebook').mean(axis = 1)

2725      375.000000
1920     4068.666667
3402     9000.000000
2779        8.333333
4312    86936.000000
dtype: float64

In [187]:
movie.loc[4312]['movie_title']

'Kickboxer: Vengeance'

### Grouping & Aggregation

#### Grouping by Continuous Vars

### Applying custom method

### Tidy vs Pivot

#### Stack(melt)

#### Unstack

연습문제 1. `flights` 데이터에서 (`항공사`, `출발지`) 조합들에서 `취소된 건수`의 `합계`를 Pivot Table을 이용해서 만들어보세요.

### Concatenation & Merging

### String Operation

|Format Code|Description|Examples|
|--|--|--|
|`%a`|Weekday, abbreviated|Mon, Tues, Sat|
|`%A`|Weekday, full name|Monday, Tuesday, Saturday|
|`%w`|Weekdat, decimal. 0=Sunday|1, 2, 6|
|`%d`|Day of month, zero-padded|01, 02, 21|
|`%b`|Month, abbreviated|Jan, Feb, Sep|
|`%B`|Month, full name|January, February, September|
|`%m`|Month number, zero-padded|01, 02, 09|
|`%y`|Year, without century, zero-padded|02, 95, 99|
|`%Y`|Year, with century|1990, 2020|
|`%H`|Hour(24 hour), zero-padded|01, 22|
|`%I`|Hour(12 hour), zero padded|01, 12|
|`%p`|AM or PM|AM, PM|
|`%M`|Minute, zero-padded|01, 02, 59|
|`%S`|Second, zero-padded|01, 02, 59|
|`%f`|Microsecond, zero-padded|000001, 000342, 999999|
|`%z`|UTC offset +- HHMM[SS[.ffffff]]|+0000, -1030, -3424.234|
|`%Z`|Time zone name|ITC, EST, CST|
|`%i`|Day of year, zero-padded|001, 365, 023|
|`%U`|Week # of year, zero-padded. Sunday first day of week|00, 01, 51|
|`%W`|Week # of year, zero-padded. Monday first day of week|00, 02, 51|
|`%c`|Appropriate date and time|Monday Feb 01 21:30:00 2022|
|`%x`|Appropriate Date|02/01/09|
|`%X`|Appropriate Time|21:22:00|

#### Datetime 연산

#### Datetime을 활용한 인덱싱 / 슬라이싱

#### Moving Window

# 실전문제 - 기상상황에 따른 따릉이 대여 수 데이터(마포구)

- Data Description
    - id : 고유 id
    - hour : 시간
    - temperature : 기온
    - precipitation : 비가 오지 않았으면 0, 비가 오면 1
    - windspeed : 풍속(평균)
    - humidity : 습도
    - visibility : 시정(視程), 시계(視界)(특정 기상 상태에 따른 가시성을 의미)
    - ozone : 오존
    - pm10 : 미세먼지(머리카락 굵기의 1/5에서 1/7 크기의 미세먼지)
    - pm2.5 : 미세먼지(머리카락 굵기의 1/20에서 1/30 크기의 미세먼지)
    - count : 시간에 따른 따릉이 대여 수

연습문제 1. 데이터의 컬럼명에서 `hour_bef_` 문자열은 모두 제거해보세요.

연습문제 2. 각 컬럼에서 결측값은 몇개인지 확인해보세요.

연습문제 3. 각 변수의 기초통계량 값을 확인해보세요.

연습문제 4. 자전거를 타는데 있어, 미세먼지 상태는 매우 중요하다고 판단됩니다. 미세먼지 결측값은 허용하되 나머지 결측값이 포함된 행은 제거해보세요.

연습문제 5. 데이터에서 `visibility` 값의 스케일이 다른 변수에 비해 큽니다. 변수 스케일링을 위해 `visibility`의 각 값을 평균값으로 나누어주세요.

연습문제 6. 오전 시간대(6시 ~ 12시)의 평균 기온과 평균 자전거 대여수를 확인해보세요.

연습문제 7. 자전거 대여수가 가장 많은 10개의 대여소의 기초통계량을 확인해보세요.

연습문제 8. 자전거 대여수가 가장 많은 10개 대여소의 통계량과 전체 대여소의 통계량의 유의미한 차이를 보이는 변수가 무엇인가요?

연습문제 9. 시간대별 자전거 대여수의 합과 평균을 구해보고, 가장 대여수가 많은 시간대는 언제인지 확인해보세요.